version: '3'

services: 
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000


        links:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: Password@12
