###
#
# This is main.yml playbook for zabbix_copysecond role.
# @host: Secondary_Core_Zabbix
# 
# @author: Mohd Danish
# @date:
# @version:
#
###

    - setup:
    - set_fact:
        var2: "{{ansible_default_ipv4.address}} {{ansible_hostname}}"
    - debug:
       msg: "{{var2}}"

# Get Environment variable Admin_Root
    - name: Get Environment variable Admin_Root
      set_fact:
        Admin_Root: "{{lookup('env','Admin_Root') }}"
    - debug:
       msg: "{{Admin_Root}}"    

# inserting ip and hostname of 'Secondary_Core_Zabbix' server in "newname.txt" file
    - lineinfile:
        path: "{{Admin_Root}}/newname.txt"
        line : "{{ var2 }}"
        insertafter: EOF
      delegate_to: localhost
# Added this for rollback ---------------------------------
   #   register: result
   #   ignore_errors: yes

   # - set_fact:
   #     pyresult: "3rr0rC0d3[00{{result.rc}}]"

   # - debug:
   #     msg: "{{result.stdout_lines[0]}}"

   # - set_fact:
   #     pyresult: "{{result.stdout_lines[0]}}"
   #   when: result.rc == 0

