###
#
# This playbook is including zabbix_db_install_secondary.yml playbook
# @host: Primary_DB_Zabbix
# 
# @author: sai
# @date:
# @version: 1
#
###

   # - include_tasks: cleanup.yml
   # - include_tasks: api.yml

# including task zabbix_db_install_primary.yml
  - include_tasks: zabbix_db_config_secondary.yml
