# Generated by Django 3.2.3 on 2021-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('mobile', models.EmailField(max_length=20)),
                ('position', models.CharField(max_length=60)),
                ('exprience', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
