###
#
# This is the zabbix_mysql_DB_Master_Config.yml playbook which is getting executed
# @host: Primary_DB_Zabbix
# 
# @author:Satish Kumar
# @date:
# @version: 2.0
#
###   


   # - include_tasks: api.yml

   - setup:
   - name: Get Environment variable Admin_Root
     set_fact:
       Admin_Root: "{{lookup('env','Admin_Root') }}"
   - debug:
      msg: "{{Admin_Root}}"

# # including vars environment.yml
#    - include_vars: "{{Admin_Root}}/Portal_Scripts/Bin/environment.yml"
#    - debug:
#        msg: Zabbix DB precheck passed on "{{ ansible_hostname }}"
#    - set_fact:
#        db_ip: "{{ ansible_default_ipv4.address }}"
#        cacheable: true

   - name: Print the name of DB node
     set_fact:
       db_ip: "{{ item }}" 
     with_items:
       - "{{ groups['Primary_DB_Zabbix'] }}"
       
# database restore 
   - name: copy zabbix scripts
     copy:
       src: "{{Admin_Root }}/iDeploy/tools/zabbix_5.0/zabbix/Bin/Configurations/zabbix_bkp.sql"
       dest: "{{ ansible_env.Admin_Root}}/zabbix/Bin/Configurations/"
   - debug:
         msg: "DB Restore File  successfully"

# Executing mysql_db_ha_config_primary.py for Zabbix DB installation
   - command: python3.7 Zabbix_Mysql_DB_Slave.py "Secondary" "{{ db_ip }}"
     args:
       chdir: "{{ ansible_env.Admin_Root }}/zabbix/Bin/Configurations"

  
       
# Added this for rollback ---------------------------------
     register: result
     ignore_errors: yes

   - set_fact:
       pyresult: "3rr0rC0d3[00{{result.rc}}]"

   - debug:
       msg: "{{result.stdout_lines[0]}}"

   - set_fact:
       pyresult: "{{result.stdout_lines[0]}}"
     when: result.rc == 0



# storing all files from output folder to a found_files variable