###
#
# This is the zabbix_core_configuration.yml playbook which is getting executed
# @host: All
# 
# @author: Sankar
# @date:  05-Oct-2020
# @version: V.1
#
###
  
  - setup:
  - set_fact: 
      Admin_Root: "{{lookup('env','Admin_Root')}}"
##core server ip
#  - name: Print the name of core node
#    set_fact:
#      Zabbix_Server: "{{ item }}"
#    with_items:
#      - "{{ groups ['Primary_Core_Zabbix'] }}"

#core server ip
  - name: Print the name of core node
    set_fact:
      Proxy_Server: "{{ item }}"
    with_items:
      - "{{ groups ['Primary_Proxy_Zabbix'] }}"

#smtp
  - name: Running script for onboard
    command: python3.7 Zabbix_Agent.py "Primary" "{{ Proxy_Server }}"
    args:
      chdir: "{{ ansible_env.Admin_Root }}/zabbix/Bin/Install"

# Added this for rollback ---------------------------------
    register: result
    ignore_errors: yes

  - set_fact:
      pyresult: "3rr0rC0d3[00{{result.rc}}]"

  - debug:
      msg: "{{result.stdout_lines[0]}}"

  - set_fact:
      pyresult: "{{result.stdout_lines[0]}}"
    when: result.rc == 0


