###
#
# @host:Secondary_Core_Zabbix
# 
# @author: Sai
# @date:
# @version: 1
#
###   


  - setup:
  - set_fact:
      Admin_Root: "{{lookup('env','Admin_Root')}}"
#  - include_vars: "{{Admin_Root}}/Portal_Scripts/Bin/environment.yml"


# executing script for zabbix core ssl configuration
  - name: Running script for zabbix core ssl configuration
    command: python3.7 Zabbix_SSL_Config.py "Secondary"
    args:
      chdir: "{{ ansible_env.Admin_Root }}/zabbix/Bin/Configurations"



# Added this for rollback ---------------------------------
    register: result
    ignore_errors: yes

  - set_fact:
      pyresult: "3rr0rC0d3[00{{result.rc}}]"

  - debug:
      msg: "{{result.stdout_lines[0]}}"

  - set_fact:
      pyresult: "{{result.stdout_lines[0]}}"
    when: result.rc == 0