###
#
# This playbook is including zabbix_core_install_secondary.yml playbook
# @host: Secondary_Core_Zabbix
# 
# @author: sai
# @date:
# @version: 1
#
### 


 # - debug:
 #    msg: "in main.yml"
 # - include_tasks: pre_flight.yml

# including tasks zabbix_core_install_secondary.yml
 - include_tasks: zabbix_core_install_secondary.yml
